image: maven:latest

stages:
  - build
  - test
  - run
  - validate

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn package

test:
  stage: test
  script:
    - mvn test

run:
  stage: run
  script:
    - mvn compile

validate:
  stage: validate
  script:
    - mvn validate