image: maven:latest

stages:
  - build
  - test
  - run
  - check
  - validate

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn package

test:
  stage: test
  script:
    - mvn test

run:
  stage: run
  script:
    - mvn compile

check:
  stage: check
  script:
    - mvn site

validate:
  stage: validate
  script:
    - mvn validate